### PR TITLE
Base for now

### PR DESCRIPTION
**Pull request by ghost**
this is a test

### CODE REVIEW

**Comment by Nabir14** [comment]
Thanks for trying to implement the makefile but you downgraded the project and removed the important disk load and string function code and created a different bootloader loading from floppy disk so I can't approve sorry

**Comment by Nabir14** [comment]
Closing pull request for being out of project

**Comment by ghost** [comment]
Wtf

**Comment by ghost** [comment]
Its the same thing?

**Comment by ghost** [comment]
I just implemented fat, early fat meaning no need to load disk for now.

**Comment by Nabir14** [comment]
> I just implemented fat, early fat meaning no need to load disk for now.

I fixed the hard disk problem so I don't need it because load disk is working

**Comment by Nabir14** [comment]
> I just implemented fat, early fat meaning no need to load disk for now.

I don't need that because I fixed the hard disk problem and load disk is now working

**Pull request closed without merging**
